name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ui-tests:
    uses: ./.github/workflows/template-playwright.yml
    with:
      test-path: tests/ui
      project-name: ui

  api-tests:
    uses: ./.github/workflows/template-playwright.yml
    with:
      test-path: tests/api
      project-name: api
